# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20181007_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post_image',
            new_name='post',
        ),
    ]
